version: "3.8"
services:
  flask_server:
    image: digitme2/oee_webapp
    ports:
      - "8000:8000"
    volumes:
      - type: volume
        source: oee_appdata_vol
        target: /home/appdata
  redis:
    image: redis
    ports:
      - "6379:6379"
  nginx:
    image: nginx:1.19
    depends_on:
      - "flask_server"
    volumes:
      - type: volume
        source: oee_appdata_vol
        target: /etc/nginx/conf.d
        volume:
          nocopy: true
    ports:
      - "80:80"

volumes:
  oee_appdata_vol:

