FROM python:3.8

RUN adduser --disabled-password --gecos "" oee

WORKDIR /home/oee_webapp

COPY requirements.txt requirements.txt
RUN python -m venv venv
RUN venv/bin/pip install -r requirements.txt
RUN venv/bin/pip install gunicorn

COPY app app
COPY migrations migrations
COPY webapp.py config.py start.sh ./
RUN chmod +x start.sh

ENV FLASK_APP webapp.py

RUN chown -R oee:oee ./
USER oee

EXPOSE 8000
ENTRYPOINT ["./start.sh"]
