# Run this docker-compose file to build the app
version: "3.3"
services:
  oee_webapp:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 8000
    environment:
      # Demo mode will make fake data
      DEMO_MODE: "true"
      # When using a SQLite database, use the date as the db name. This effectively resets the database every day
      USE_FRESH_DAILY_SQLITE_DB: "true"
      # How often to fake the data (too often, and it will take a long time when back-filling)
      DATA_SIMULATION_FREQUENCY_SECONDS: 60
      # How many days worth of fake data to fill in when the server cold starts
      DAYS_BACKFILL: 3
  redis:
    image: redis

