version: "3.8"
services:
  flask_server:
    image: digitme2/oee_webapp
    volumes:
      - oee_appdata_vol:/home/appdata
  redis:
    image: redis
    ports:
      - "6379:6379"
  nginx_oee:
    build: ../nginx
    depends_on:
      - "flask_server"
    volumes:
      - type: volume
        source: oee_appdata_vol
        target: /etc/nginx/conf.d
        volume:
          nocopy: true
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80

volumes:
  oee_appdata_vol:
