"""Initial migration

Revision ID: 536e127eb79d
Revises: 
Create Date: 2022-03-29 15:38:49.914232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536e127eb79d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('autofill_job_start_input', sa.Boolean(), nullable=True))
    op.add_column('machine', sa.Column('autofill_job_start_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'autofill_job_start_amount')
    op.drop_column('machine', 'autofill_job_start_input')
    # ### end Alembic commands ###
