version: "3.8"
services:
  oee_webapp:
    image: digitme2/oee_webapp:single-image
    volumes:
      - oee_appdata_vol:/data
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 8000
    environment:
      DEMO_MODE: true
      DATA_SIMULATION_FREQUENCY_SECONDS: 60
      DAYS_BACKFILL: 3
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  oee_appdata_vol:
